name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish-android:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
        - uses: actions/checkout@v4
          with:
            submodules: 'true'

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
              distribution: 'zulu'
              java-version: '17'

        - name: Setup Android SDK
          uses: android-actions/setup-android@v3

        - name: Install NDK
          run: sdkmanager "ndk;27.0.11902837"

        - name: setup node
          uses: actions/setup-node@v4
          with:
              node-version: lts/*

        - name: install Rust nightly
          uses: dtolnay/rust-toolchain@nightly
          with:
              targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android,wasm32-unknown-unknown

        - name: Install dependencies
          run: |
              sudo apt-get update
              sudo apt-get install -y libwebkit2gtk-4.1-dev \
                build-essential \
                curl \
                wget \
                file \
                libxdo-dev \
                libssl-dev \
                libayatana-appindicator3-dev \
                librsvg2-dev
              rustup default nightly
        
        - uses: cargo-bins/cargo-binstall@main

        - name: Install trunk + others
          run: |
              cargo binstall -y trunk tauri-cli cargo-generate wasm-bindgen-cli cargo-leptos
              npm install -g sass

        - name: Extract android signing key from env
          run: |
              echo "${{ secrets.ANDROID_RELEASE_KEYSTORE }}" > src-tauri/gen/android/release.jks.base64
              base64 -d src-tauri/gen/android/release.jks.base64 > src-tauri/gen/android/release.decrypted.jks
              echo "password=${{ secrets.ANDROID_RELEASE_PASSWORD }}" > src-tauri/gen/android/keystore.properties
              echo "keyAlias=${{ secrets.ANDROID_RELEASE_KEY }}" >> src-tauri/gen/android/keystore.properties
              echo "storeFile=release.decrypted.jks" >> src-tauri/gen/android/keystore.properties

        - name: Extract some locs
          run: |
              echo "${{ secrets.HOME }}" > src-tauri/locations/home.geojson.base64
              base64 -d src-tauri/locations/home.geojson.base64 > src-tauri/locations/home.geojson
              echo "${{ secrets.WORK }}" > src-tauri/locations/work.geojson.base64
              base64 -d src-tauri/locations/work.geojson.base64 > src-tauri/locations/work.geojson
              echo "${{ secrets.SCHOOL }}" > src-tauri/locations/school.geojson.base64
              base64 -d src-tauri/locations/school.geojson.base64 > src-tauri/locations/school.geojson

        - name: Build app bundle
          run: |
              cargo tauri android build -v --aab
          env:
              NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/27.0.11902837

        - name: Sign APK
          run: |
              ${{ env.ANDROID_HOME }}/build-tools/34.0.0/apksigner sign --ks src-tauri/gen/android/release.decrypted.jks \
                --ks-key-alias ${{ secrets.ANDROID_RELEASE_KEY }} \
                --ks-pass pass:${{ secrets.ANDROID_RELEASE_PASSWORD }} \
                --key-pass pass:${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }} \
                --out src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-signed.apk \
                src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk

        - name: Get project version
          run: |
              echo "VERSION=$(jq -r .bundle.android.versionCode src-tauri/tauri.conf.json)" >> $GITHUB_ENV

        - name: Rename APK file
          run: |
              mv ./src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab ./src-tauri/gen/android/app/build/outputs/bundle/universalRelease/rust-tauri-app-${{ env.VERSION }}.apk

        - name: Publish
          uses: softprops/action-gh-release@v1
          with:
              draft: true
              name: App v${{ env.VERSION }}
              tag_name: v${{ env.VERSION }}
              generate_release_notes: true
              files: |
                  ./src-tauri/gen/android/app/build/outputs/bundle/universalRelease/rust-tauri-app-${{ env.VERSION }}.apk